### ISSUE TITLE
Unexpected error running initialize() for stromer

### ISSUE THREAD

**Issue by SirJohnDoe** [jmnieuwhoff/homeassistant#2]
It works well, until it doesnt. After a few hours of running it, I get this error:

> 2021-01-27 14:29:38.186338 WARNING stromer: ------------------------------------------------------------
> 2021-01-27 14:29:38.188058 WARNING stromer: Unexpected error running initialize() for stromer
> 2021-01-27 14:29:38.189430 WARNING stromer: ------------------------------------------------------------
> 2021-01-27 14:29:38.204991 WARNING stromer: Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 150, in initialize_app
>     await utils.run_in_executor(self, init)
>   File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
>     response = future.result()
>   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/appdaemon/apps/stromer/stromer.py", line 90, in initialize
>     code = get_code(client_id, username, password)
>   File "/config/appdaemon/apps/stromer/stromer.py", line 52, in get_code
>     res = s.send(res.next, allow_redirects=False)
>   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
>     hooks = request.hooks
> AttributeError: 'NoneType' object has no attribute 'hooks'
> 2021-01-27 14:29:38.206563 WARNING stromer: ------------------------------------------------------------
> 2021-01-27 14:29:38.211860 INFO AppDaemon: App initialization complete

Any idea what could be causing this?

**Comment by johannusNL** [comment]
Hi, i didn't have time yet to find out whats causing this issue. I tried several things, like delays in between steps etc. But no solution yet.

**Comment by SirJohnDoe** [comment]
Hey, thanks for you reply.

I fixed it like this: I changed the sleeptimer at the end to a simple 'time.sleep(300)', I read somewhere that the time.time() in a formula can sometimes cause errors depending on the sytem clock (timezone etc.). I think every 5 minutes is plenty, in practice it takes 5 minutes 25 seconds for the next run to finish. It could be that the previous had no effect whatsoever, because I also added this: an exception for the Attribute error, so that it terminates on an error (after which I think AppDaemon will restart, instead of fail to initialise). But I think the former change fixed it, because I have been running for at least 24h (I restart HA quite often lately ;-) and I don't see any "ERROR" in the logs.

Don't take my word for granted though, I've never written a Python script and this is just some Googling. It seems to work though :-3

```
#!/usr/bin/env python3
import requests
from urllib.parse import urlencode, parse_qs, splitquery
from datetime import datetime
import json
import time
import appdaemon.plugins.hass.hassapi as hass

#
# Stromer app
#

password =
username =
client_id = 
client_secret = 

class stromer(hass.Hass):
    def initialize(self):
        starttime=time.time()
        while True:
            try:
                def get_code(client_id, username, password):
                    MAX_RETRIES = 20  #!Added [link]
                    session = requests.Session()
                    adapter = requests.adapters.HTTPAdapter(max_retries=MAX_RETRIES)
                    session.mount('https://', adapter)
                    session.mount('http://', adapter)
                    url = "https://api3.stromer-portal.ch/users/login/"
                    s = requests.session()
                    res = s.get(url)
                    s.cookies
                
                    qs = urlencode({
                        "client_id":
                        client_id,
                        "response_type":
                        "code",
                        "redirect_url":
                        "stromerauth://auth",
                        "scope":
                        "bikeposition bikestatus bikeconfiguration bikelock biketheft bikedata bikepin bikeblink userprofile",
                    })
                
                    data = {
                        "password": password,
                        "username": username,
                        "csrfmiddlewaretoken": s.cookies.get("csrftoken"),
                        "next": "/o/authorize/?" + qs,
                    }
                
                    res = s.post(url, data=data, headers=dict(Referer=url), allow_redirects=False)
                    res = s.send(res.next, allow_redirects=False)
                    _, qs = splitquery(res.headers["Location"])
                    code = parse_qs(qs)["code"][0]
                    return code
                
                
                def get_access_token(client_id, client_secret, code):
                    url = "https://api3.stromer-portal.ch//o/token/"
                    params = {
                        "grant_type": "authorization_code",
                        "client_id": client_id,
                        "client_secret": client_secret,
                        "code": code,
                        "redirect_uri": "stromerauth://auth",
                    }
                
                    res = requests.post(url, params=params)
                    return res.json()["access_token"]
                
                
                def call_api(access_token, endpoint, params={}):
                    url = "https://api3.stromer-portal.ch/rapi/mobile/v2/%s" % endpoint
                    headers = {"Authorization": "Bearer %s" % access_token}
                    res = requests.get(url, headers=headers, params={})
                    data = res.json()["data"]
                    if isinstance(data, list):
                        return data[0]
                    else:
                        return data
                
                
                def call_bike(access_token, bike, endpoint, cached="false"):
                    endpoint = 'bike/%s/%s' % (bike["bikeid"], endpoint)
                    params = {'cached': '%s' % cached}
                    state = call_api(access_token, endpoint, params)
                    return state
                
                
                code = get_code(client_id, username, password)
                access_token = get_access_token(client_id, client_secret, code)
                bike = call_api(access_token, "bike")
                state = call_bike(access_token, bike, 'state/')
                position = call_bike(access_token, bike, 'position/')
     
                self.set_state("sensor.stromer_current_speed", state = state['bike_speed'])
                self.set_state("sensor.stromer_trip_distance", state = state['trip_distance'])
                self.set_state("sensor.stromer_avg_speed_trip", state = state['average_speed_trip'])
                self.set_state("sensor.stromer_triptime", state = state['trip_time'])
                self.set_state("sensor.stromer_battery_chargelevel", state = state['battery_SOC'])
                self.set_state("sensor.stromer_lockstate", state = state['lock_flag'])
                self.set_state("sensor.stromer_geocoded_location", state = '', attributes = {"altitude": position['altitude'], "latitude": position['latitude'], "longitude": position['longitude'], "icon": 'mdi:map'})
                self.set_state("sensor.stromer_batterytemp", state = state['battery_temp'])
                self.set_state("sensor.stromer_motortemp", state = state['motor_temp'])
                self.set_state("sensor.stromer_battery_healthstate", state = state['battery_health'])
                self.set_state("sensor.stromer_battery_poweron_cycles", state = state['power_on_cycles'])
                self.set_state("sensor.stromer_totaldistance", state = state['total_distance'])
                self.set_state("sensor.stromer_totaltime", state = state['total_time'])
                self.set_state("sensor.stromer_avg_energy", state = state['average_energy_consumption'])
                self.set_state("sensor.stromer_softwareversion", state = state['suiversion'])
                self.set_state("sensor.stromer_lastupdated", state = state['rcvts'])
                self.log("Omni data bijgewerkt")
                time.sleep(300)
            except AttributeError:
                self.log("ERROR")
                terminate()
```

**Comment by johannusNL** [comment]
That's great. I will try it too in my script. This is my first and only python experience too :)
Let's heads up in a few weeks to share our findings. 

Thanks!

**Comment by SirJohnDoe** [comment]
I've been running it for the past couple days now without any problems. The Attribute Error hasn't returned, but it did a while ago and I found out that the 'terminate()' function needs to be created first so the script above gives an error (although Omni keeps updating) because 'terminate()' doesn't mean anything. Aside from the Attribute Error, I get a JSONDecodeError every few days, but as the next run(s) are succesful again it doesn't matter.

I've changed the script to this, with 1 minute sleep between each run (to see if it'd increase errors, but it didn't):

```
#!/usr/bin/env python3
import requests
from urllib.parse import urlencode, parse_qs, splitquery
from datetime import datetime
import json
import time
import appdaemon.plugins.hass.hassapi as hass

#
# Stromer app
#

password =
username =
client_id =
client_secret =

class stromer(hass.Hass):
    def initialize(self):
        starttime=time.time()
        while True:
            try:
                def get_code(client_id, username, password):
                    MAX_RETRIES = 20  #!Added https://stackoverflow.com/questions/33895739/python-requests-module-error-cant-load-any-url-remote-end-closed-connection
                    session = requests.Session()
                    adapter = requests.adapters.HTTPAdapter(max_retries=MAX_RETRIES)
                    session.mount('https://', adapter)
                    session.mount('http://', adapter)
                    url = "https://api3.stromer-portal.ch/users/login/"
                    s = requests.session()
                    res = s.get(url)
                    s.cookies
                
                    qs = urlencode({
                        "client_id":
                        client_id,
                        "response_type":
                        "code",
                        "redirect_url":
                        "stromerauth://auth",
                        "scope":
                        "bikeposition bikestatus bikeconfiguration bikelock biketheft bikedata bikepin bikeblink userprofile",
                    })
                
                    data = {
                        "password": password,
                        "username": username,
                        "csrfmiddlewaretoken": s.cookies.get("csrftoken"),
                        "next": "/o/authorize/?" + qs,
                    }
                
                    res = s.post(url, data=data, headers=dict(Referer=url), allow_redirects=False)
                    res = s.send(res.next, allow_redirects=False)
                    _, qs = splitquery(res.headers["Location"])
                    code = parse_qs(qs)["code"][0]
                    return code
                
                
                def get_access_token(client_id, client_secret, code):
                    url = "https://api3.stromer-portal.ch//o/token/"
                    params = {
                        "grant_type": "authorization_code",
                        "client_id": client_id,
                        "client_secret": client_secret,
                        "code": code,
                        "redirect_uri": "stromerauth://auth",
                    }
                
                    res = requests.post(url, params=params)
                    return res.json()["access_token"]
                
                
                def call_api(access_token, endpoint, params={}):
                    url = "https://api3.stromer-portal.ch/rapi/mobile/v2/%s" % endpoint
                    headers = {"Authorization": "Bearer %s" % access_token}
                    res = requests.get(url, headers=headers, params={})
                    data = res.json()["data"]
                    if isinstance(data, list):
                        return data[0]
                    else:
                        return data
                
                
                def call_bike(access_token, bike, endpoint, cached="false"):
                    endpoint = 'bike/%s/%s' % (bike["bikeid"], endpoint)
                    params = {'cached': '%s' % cached}
                    state = call_api(access_token, endpoint, params)
                    return state
                
                
                code = get_code(client_id, username, password)
                access_token = get_access_token(client_id, client_secret, code)
                bike = call_api(access_token, "bike")
                state = call_bike(access_token, bike, 'state/')
                position = call_bike(access_token, bike, 'position/')
     
                self.set_state("sensor.stromer_current_speed", state = state['bike_speed'])
                self.set_state("sensor.stromer_trip_distance", state = state['trip_distance'])
                self.set_state("sensor.stromer_avg_speed_trip", state = state['average_speed_trip'])
                self.set_state("sensor.stromer_triptime", state = state['trip_time'])
                self.set_state("sensor.stromer_battery_chargelevel", state = state['battery_SOC'])
                self.set_state("sensor.stromer_lockstate", state = state['lock_flag'])
                self.set_state("sensor.stromer_geocoded_location", state = '', attributes = {"altitude": position['altitude'], "latitude": position['latitude'], "longitude": position['longitude'], "icon": 'mdi:map'})
                self.set_state("sensor.stromer_batterytemp", state = state['battery_temp'])
                self.set_state("sensor.stromer_motortemp", state = state['motor_temp'])
                self.set_state("sensor.stromer_battery_healthstate", state = state['battery_health'])
                self.set_state("sensor.stromer_battery_poweron_cycles", state = state['power_on_cycles'])
                self.set_state("sensor.stromer_totaldistance", state = state['total_distance'])
                self.set_state("sensor.stromer_totaltime", state = state['total_time'])
                self.set_state("sensor.stromer_avg_energy", state = state['average_energy_consumption'])
                self.set_state("sensor.stromer_softwareversion", state = state['suiversion'])
                self.set_state("sensor.stromer_lastupdated", state = state['rcvts'])
                self.log("Omni data bijgewerkt")
                time.sleep(60)
            except AttributeError:
                self.log("ERROR")
                time.sleep(30)
                continue
```
